"""add ee plans subscriptions

Revision ID: 50665b9dafa6
Revises: c8d8e9a5d394
Create Date: 2026-08-27 13:46:14.099549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50665b9dafa6'
down_revision: Union[str, Sequence[str], None] = 'c8d8e9a5d394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('max_cpu_per_instance', sa.String(length=16), nullable=False),
    sa.Column('max_mem_per_instance', sa.String(length=16), nullable=False),
    sa.Column('max_storage_per_instance', sa.String(length=16), nullable=False),
    sa.Column('max_total_cpu', sa.String(length=16), nullable=False),
    sa.Column('max_total_mem', sa.String(length=16), nullable=False),
    sa.Column('max_total_storage', sa.String(length=16), nullable=False),
    sa.Column('allowed_specs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dedicated_cluster', sa.Boolean(), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_deleted_at'), 'plans', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.create_table('subscriptions',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('plan_name', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_deleted_at'), 'subscriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_org_id'), 'subscriptions', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_org_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_deleted_at'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_deleted_at'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
