"""conversation and message workspace nullable for direct chat

Revision ID: 655466428d57
Revises: bbd32dcd7f62
Create Date: 2026-09-01 09:01:35.922012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655466428d57'
down_revision: Union[str, Sequence[str], None] = 'bbd32dcd7f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('workspace_messages', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # autogenerate 同时检出的 uq_genes_name_* 表达式差异是文本归一化噪音，已剔除（同 bbd32dcd7f62）
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_messages', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('conversations', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # ### end Alembic commands ###
