"""mission priority and fuse_ack_count

Revision ID: 6bb326ed2ac7
Revises: 655466428d57
Create Date: 2026-09-02 11:59:50.087655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bb326ed2ac7'
down_revision: Union[str, Sequence[str], None] = '655466428d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('fuse_ack_count', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('missions', sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.create_index(op.f('ix_missions_priority'), 'missions', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_missions_priority'), table_name='missions')
    op.drop_column('missions', 'priority')
    op.drop_column('missions', 'fuse_ack_count')
    # ### end Alembic commands ###
