"""add external agent invocations

Revision ID: 6f131501f1cc
Revises: 72c3f6496399
Create Date: 2026-08-24 17:20:29.707354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f131501f1cc'
down_revision: Union[str, Sequence[str], None] = '72c3f6496399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_agent_invocations',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('function_id', sa.String(length=36), nullable=True),
    sa.Column('function_name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('params_summary', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('upstream_status', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['external_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_agent_invocations_agent_id'), 'external_agent_invocations', ['agent_id'], unique=False)
    op.create_index('ix_external_agent_invocations_agent_user_created', 'external_agent_invocations', ['agent_id', 'user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_external_agent_invocations_deleted_at'), 'external_agent_invocations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_external_agent_invocations_user_id'), 'external_agent_invocations', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # 注：autogenerate 同时检出的 uq_genes_name_* 表达式差异（lower(TRIM(BOTH FROM name)) 与
    # lower(trim(name)) 语义等价）是文本归一化噪音，已剔除，不属于本迁移。


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_agent_invocations_user_id'), table_name='external_agent_invocations')
    op.drop_index(op.f('ix_external_agent_invocations_deleted_at'), table_name='external_agent_invocations')
    op.drop_index('ix_external_agent_invocations_agent_user_created', table_name='external_agent_invocations')
    op.drop_index(op.f('ix_external_agent_invocations_agent_id'), table_name='external_agent_invocations')
    op.drop_table('external_agent_invocations')
    # ### end Alembic commands ###
