"""mission templates and execution mode

Revision ID: ba10afef6300
Revises: 6bb326ed2ac7
Create Date: 2026-09-02 19:19:51.848364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba10afef6300'
down_revision: Union[str, Sequence[str], None] = '6bb326ed2ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission_templates',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brief_template', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('escalation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mission_type', sa.String(length=16), server_default='standard', nullable=False),
    sa.Column('execution_mode', sa.String(length=16), server_default='auto', nullable=False),
    sa.Column('created_from_mission_id', sa.String(length=36), nullable=True),
    sa.Column('usage_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_from_mission_id'], ['missions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_templates_deleted_at'), 'mission_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mission_templates_org_id'), 'mission_templates', ['org_id'], unique=False)
    op.create_index(op.f('ix_mission_templates_workspace_id'), 'mission_templates', ['workspace_id'], unique=False)
    op.create_table('mission_template_nodes',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('capability_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['mission_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_template_nodes_deleted_at'), 'mission_template_nodes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mission_template_nodes_template_id'), 'mission_template_nodes', ['template_id'], unique=False)
    op.create_index('uq_mission_template_nodes_template_seq', 'mission_template_nodes', ['template_id', 'seq'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.add_column('missions', sa.Column('execution_mode', sa.String(length=16), server_default='auto', nullable=False))
    op.add_column('missions', sa.Column('paused_for_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('missions', 'paused_for_review')
    op.drop_column('missions', 'execution_mode')
    op.drop_index('uq_mission_template_nodes_template_seq', table_name='mission_template_nodes', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_mission_template_nodes_template_id'), table_name='mission_template_nodes')
    op.drop_index(op.f('ix_mission_template_nodes_deleted_at'), table_name='mission_template_nodes')
    op.drop_table('mission_template_nodes')
    op.drop_index(op.f('ix_mission_templates_workspace_id'), table_name='mission_templates')
    op.drop_index(op.f('ix_mission_templates_org_id'), table_name='mission_templates')
    op.drop_index(op.f('ix_mission_templates_deleted_at'), table_name='mission_templates')
    op.drop_table('mission_templates')
    # ### end Alembic commands ###
