"""add mission tables

Revision ID: bbd32dcd7f62
Revises: 50665b9dafa6
Create Date: 2026-08-29 11:41:40.096351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# revision identifiers, used by Alembic.
revision: str = 'bbd32dcd7f62'
down_revision: Union[str, Sequence[str], None] = '50665b9dafa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 平台预置能力词表（设计 §3.6，org_id=NULL 表示平台级，org 管理员可另建自己的词表）。
# description 供编排器 prompt 使用，说明标签语义。
PLATFORM_CAPABILITY_TAGS = [
    ("backend", "后端开发", "Backend", "服务端程序与 API 设计、数据库建模与编码实现"),
    ("frontend", "前端开发", "Frontend", "Web 页面开发、交互实现与样式还原"),
    ("fullstack", "全栈开发", "Full-stack", "前后端一体的小型应用或工具开发"),
    ("mobile", "移动端开发", "Mobile", "移动端 App 或小程序开发"),
    ("ui-design", "UI 设计", "UI Design", "界面视觉设计、原型与设计稿产出"),
    ("data-analysis", "数据分析", "Data Analysis", "数据清洗、统计分析与图表结论产出"),
    ("data-engineering", "数据工程", "Data Engineering", "数据管道、ETL 与数据仓库建设"),
    ("devops", "运维部署", "DevOps", "部署、容器编排、CI/CD 与环境维护"),
    ("testing", "测试", "Testing", "测试用例设计、自动化测试编写与缺陷验证"),
    ("security", "安全", "Security", "安全审查、漏洞分析与加固建议"),
    ("payment", "支付", "Payment", "支付、对账、清结算等资金相关功能开发"),
    ("e-commerce", "电商", "E-commerce", "电商业务功能（商品、订单、营销）开发"),
    ("copywriting", "文案写作", "Copywriting", "营销文案、品牌话术与内容创作"),
    ("document-writing", "文档撰写", "Document Writing", "方案文档、报告、说明书的撰写与排版"),
    ("translation", "翻译", "Translation", "中英文等多语种互译与本地化"),
    ("research", "调研", "Research", "行业或技术调研、资料搜集与摘要提炼"),
    ("project-management", "项目管理", "Project Management", "任务拆解、进度跟踪与风险同步"),
    ("customer-service", "客户服务", "Customer Service", "客户咨询应答、工单处理与话术维护"),
    ("automation", "自动化脚本", "Automation", "重复流程的脚本化与自动化处理"),
    ("integration", "系统集成", "Integration", "第三方系统对接、API 集成与联调"),
]


def _seed_platform_capability_tags() -> None:
    """播种平台预置能力词表（幂等，先例：7318dfeb7c3f 的 sa.table + exists 检查）。

    注意：org_id 为 NULL 时唯一索引不拦截重复（PG 唯一索引里 NULL 不相等），
    幂等必须靠 exists 检查，不能依赖 uq_capability_tags_org_tag。
    """
    conn = op.get_bind()
    t = sa.table(
        "capability_tags",
        sa.column("id", sa.String),
        sa.column("org_id", sa.String),
        sa.column("tag", sa.String),
        sa.column("label_zh", sa.String),
        sa.column("label_en", sa.String),
        sa.column("description", sa.String),
        sa.column("status", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )
    for tag, label_zh, label_en, description in PLATFORM_CAPABILITY_TAGS:
        exists = conn.execute(
            sa.select(sa.literal(1)).select_from(t).where(
                t.c.org_id.is_(None), t.c.tag == tag,
            )
        ).scalar()
        if not exists:
            conn.execute(sa.insert(t).values(
                id=str(uuid.uuid4()), org_id=None, tag=tag,
                label_zh=label_zh, label_en=label_en, description=description,
                status="active",
                created_at=sa.func.now(), updated_at=sa.func.now(),
            ))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_tags',
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('label_zh', sa.String(length=100), nullable=True),
    sa.Column('label_en', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_tags_deleted_at'), 'capability_tags', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_capability_tags_tag'), 'capability_tags', ['tag'], unique=False)
    op.create_index('uq_capability_tags_org_tag', 'capability_tags', ['org_id', 'tag'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('mission_org_configs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_ttl_days', sa.Integer(), server_default=sa.text('14'), nullable=False),
    sa.Column('mission_token_fuse', sa.Integer(), nullable=True),
    sa.Column('escalation_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_org_configs_deleted_at'), 'mission_org_configs', ['deleted_at'], unique=False)
    op.create_index('uq_mission_org_configs_org', 'mission_org_configs', ['org_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('missions',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('mission_type', sa.String(length=16), server_default='standard', nullable=False),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('escalation_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_ttl_days', sa.Integer(), nullable=True),
    sa.Column('token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('prompt_token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fuse_acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('coordinator_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_deleted_at'), 'missions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_missions_org_id'), 'missions', ['org_id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_index(op.f('ix_missions_workspace_id'), 'missions', ['workspace_id'], unique=False)
    op.create_table('mission_event_counters',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('next_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mission_id')
    )
    op.create_table('mission_nodes',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('capability_tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('assigned_instance_id', sa.String(length=36), nullable=True),
    sa.Column('match_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('session_key', sa.String(length=120), nullable=False),
    sa.Column('last_task_id', sa.String(length=64), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('prompt_token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completion_token_cost', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_instance_id'], ['instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='任务空间执行节点，按 capability_tags 匹配 AI 员工派发'
    )
    op.create_index(op.f('ix_mission_nodes_deleted_at'), 'mission_nodes', ['deleted_at'], unique=False)
    op.create_index('ix_mission_nodes_instance_status', 'mission_nodes', ['assigned_instance_id', 'status'], unique=False)
    op.create_index(op.f('ix_mission_nodes_mission_id'), 'mission_nodes', ['mission_id'], unique=False)
    op.create_index('ix_mission_nodes_mission_status', 'mission_nodes', ['mission_id', 'status'], unique=False)
    op.create_index(op.f('ix_mission_nodes_org_id'), 'mission_nodes', ['org_id'], unique=False)
    op.create_index(op.f('ix_mission_nodes_status'), 'mission_nodes', ['status'], unique=False)
    op.create_table('mission_artifacts',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('retention', sa.String(length=16), server_default='quarantine', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('produced_by_instance_id', sa.String(length=36), nullable=True),
    sa.Column('promoted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['mission_nodes.id'], ),
    sa.ForeignKeyConstraint(['produced_by_instance_id'], ['instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['promoted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_artifacts_deleted_at'), 'mission_artifacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mission_artifacts_mission_id'), 'mission_artifacts', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_artifacts_node_id'), 'mission_artifacts', ['node_id'], unique=False)
    op.create_index(op.f('ix_mission_artifacts_org_id'), 'mission_artifacts', ['org_id'], unique=False)
    op.create_index('ix_mission_artifacts_retention_expires', 'mission_artifacts', ['retention', 'expires_at'], unique=False)
    op.create_table('mission_events',
    sa.Column('mission_id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='both', nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['mission_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_deleted_at'), 'mission_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_mission_events_mission_id'), 'mission_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_events_node_id'), 'mission_events', ['node_id'], unique=False)
    op.create_index(op.f('ix_mission_events_org_id'), 'mission_events', ['org_id'], unique=False)
    op.create_index('uq_mission_events_mission_seq', 'mission_events', ['mission_id', 'seq'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ── 平台预置能力词表 seed（org_id=NULL，设计 §3.6）──
    _seed_platform_capability_tags()
    # autogenerate 同时检出的 uq_genes_name_* 表达式差异（lower(TRIM(BOTH FROM name))
    # vs lower(trim(name))）是文本归一化噪音，已剔除（同 d2c0a08b94d9 的处理）
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_mission_events_mission_seq', table_name='mission_events', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_mission_events_org_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_node_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_mission_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_deleted_at'), table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_index('ix_mission_artifacts_retention_expires', table_name='mission_artifacts')
    op.drop_index(op.f('ix_mission_artifacts_org_id'), table_name='mission_artifacts')
    op.drop_index(op.f('ix_mission_artifacts_node_id'), table_name='mission_artifacts')
    op.drop_index(op.f('ix_mission_artifacts_mission_id'), table_name='mission_artifacts')
    op.drop_index(op.f('ix_mission_artifacts_deleted_at'), table_name='mission_artifacts')
    op.drop_table('mission_artifacts')
    op.drop_index(op.f('ix_mission_nodes_status'), table_name='mission_nodes')
    op.drop_index(op.f('ix_mission_nodes_org_id'), table_name='mission_nodes')
    op.drop_index('ix_mission_nodes_mission_status', table_name='mission_nodes')
    op.drop_index(op.f('ix_mission_nodes_mission_id'), table_name='mission_nodes')
    op.drop_index('ix_mission_nodes_instance_status', table_name='mission_nodes')
    op.drop_index(op.f('ix_mission_nodes_deleted_at'), table_name='mission_nodes')
    op.drop_table('mission_nodes')
    op.drop_table('mission_event_counters')
    op.drop_index(op.f('ix_missions_workspace_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_org_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_deleted_at'), table_name='missions')
    op.drop_table('missions')
    op.drop_index('uq_mission_org_configs_org', table_name='mission_org_configs', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_mission_org_configs_deleted_at'), table_name='mission_org_configs')
    op.drop_table('mission_org_configs')
    op.drop_index('uq_capability_tags_org_tag', table_name='capability_tags', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_capability_tags_tag'), table_name='capability_tags')
    op.drop_index(op.f('ix_capability_tags_deleted_at'), table_name='capability_tags')
    op.drop_table('capability_tags')
    # ### end Alembic commands ###
