"""add gene categories

Revision ID: c8d8e9a5d394
Revises: d2c0a08b94d9
Create Date: 2026-08-27 11:35:39.091008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8d8e9a5d394'
down_revision: Union[str, Sequence[str], None] = 'd2c0a08b94d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_categories',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    comment='技能市场分类字典，管理员可编辑'
    )
    op.create_index(op.f('ix_gene_categories_deleted_at'), 'gene_categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gene_categories_name'), 'gene_categories', ['name'], unique=False)
    op.create_index('uq_gene_categories_name_active', 'gene_categories', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
    # 注：autogenerate 检出的 uq_genes_name_* 表达式差异是文本归一化噪音，已剔除（与 6f131501f1cc / d2c0a08b94d9 相同处理）


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_gene_categories_name_active', table_name='gene_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_gene_categories_name'), table_name='gene_categories')
    op.drop_index(op.f('ix_gene_categories_deleted_at'), table_name='gene_categories')
    op.drop_table('gene_categories')
    # ### end Alembic commands ###
