"""add gene market events

Revision ID: d2c0a08b94d9
Revises: 6f131501f1cc
Create Date: 2026-08-27 09:43:50.199751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c0a08b94d9'
down_revision: Union[str, Sequence[str], None] = '6f131501f1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_market_events',
    sa.Column('gene_id', sa.String(length=36), nullable=False),
    sa.Column('gene_slug', sa.String(length=255), nullable=False),
    sa.Column('gene_name', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('target_scope', sa.String(length=16), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gene_id'], ['genes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gene_market_events_deleted_at'), 'gene_market_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_gene_market_events_gene_id'), 'gene_market_events', ['gene_id'], unique=False)
    op.create_index('ix_gene_market_events_gene_type_created', 'gene_market_events', ['gene_id', 'event_type', 'created_at'], unique=False)
    op.create_index('ix_gene_market_events_type_org_created', 'gene_market_events', ['event_type', 'org_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    # 注：autogenerate 同时检出的 uq_genes_name_* 表达式差异（lower(TRIM(BOTH FROM name))
    # 与 lower(trim(name)) 语义等价）是文本归一化噪音，已剔除，不属于本迁移
    # （与 6f131501f1cc 迁移中相同的处理）。


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gene_market_events_type_org_created', table_name='gene_market_events')
    op.drop_index('ix_gene_market_events_gene_type_created', table_name='gene_market_events')
    op.drop_index(op.f('ix_gene_market_events_gene_id'), table_name='gene_market_events')
    op.drop_index(op.f('ix_gene_market_events_deleted_at'), table_name='gene_market_events')
    op.drop_table('gene_market_events')
    # ### end Alembic commands ###
